@baseUrl = http://localhost:8000/api/v1

###

# @name healthcheck
GET {{baseUrl}}/healthcheck

###

# @name ListUsers
GET {{baseUrl}}/users

###

# @name CreateUser
POST {{baseUrl}}/users

{
	"username": "user05",
	"email": "user05@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "12345678"
}

###