@baseUrl = http://localhost:8080/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODgwNDU0MzUsIm9yaWdfaWF0IjoxNTg4MDQxODM1LCJyb2xlcyI6WzJdLCJzbHVnIjoicnNjb3R0IiwidXNlcm5hbWUiOiJyU2NvdHQifQ.tx69WT15AiCaKmEy4-zu5q9bMqFebG7z-eeKUQZxUEY

###

# @name healthcheck
GET {{baseUrl}}/healthcheck

###

# @name login
POST  {{baseUrl}}/login

{
    "username": "rScott",
    "password": "12345678"
}

###

# @name ListUsers
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

###

# @name CreateUser
POST {{baseUrl}}/users
Authorization: Bearer {{token}}

{
	"username": "user01",
	"email": "user01@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "12345678"
}

###

# @name UpdateUser
PUT {{baseUrl}}/users/zwright
Authorization: Bearer {{token}}

{
	"status": "A"
}

###

# @name DeleteUser
DELETE  {{baseUrl}}/users/quia_deleniti_deleniti
Authorization: Bearer {{token}}

###

# @name ChangePassword
PUT {{baseUrl}}/users/rscott/password
Authorization: Bearer {{token}}

{
	"current_password": "12345678",
	"new_password": "password"
}

###