@baseUrl = http://localhost:8080/api/v1/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTAyMzU5MzIsIm9yaWdfaWF0IjoxNTkwMjMyMzMyLCJyb2xlcyI6WzJdLCJzbHVnIjoiZnByaWNlIiwidXNlcm5hbWUiOiJmUHJpY2UifQ.uO_SIh6lJxtxMTFErX-RrLpNbfyRxAKo7azTrv-QSBE

###

# @name GetAllUsers
GET {{baseUrl}}/?pageSize=5&page=2
Authorization: Bearer {{token}}

###

# @name GetUserBySlug
GET {{baseUrl}}/fprice
Authorization: Bearer {{token}}


###

# @name CreateUser
POST {{baseUrl}}
Authorization: Bearer {{token}}

{
	"username": "user01",
	"email": "user01@email.com",
	"firstName": "john",
	"lastName": "doe",
	"password": "12345678"
}

###

# @name UpdateUser
PUT {{baseUrl}}/fprice
Authorization: Bearer {{token}}

{
	"status": "A"
}

###

# @name DeleteUser
DELETE  {{baseUrl}}/est
Authorization: Bearer {{token}}

###

# @name ChangePassword
PUT {{baseUrl}}/fprice/password
Authorization: Bearer {{token}}

{
	"current_password": "12345678",
	"new_password": "password"
}

###

# @name UploadAvatar
PUT  {{baseUrl}}/fprice/avatar
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="golang.png"
Content-Type: image/png

< ../golang.png
--MyBoundary--